// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

/**
 * Prover model
 */
export interface Prover {
  name?: string;
  description?: string;
  identifier?: string;
  provider?: string;
  proving_scheme?: string;
  curve?: string;
  status?: string;
  note_store_id?: string /* uuid */;
  nullifier_store_id?: string /* uuid */;
  artifacts?: { [key: string]: any};
  verifier_contract?: { [key: string]: any};
}
/**
 * StoreValueResponse model
 */
export interface StoreValueResponse {
  errors?: (any /* api.Error */ | undefined)[];
  length?: number /* int */;
  root?: string;
  nullifier_key?: string;
  value?: string;
  metadata?: { [key: string]: any};
}
/**
 * ProveResponse model
 */
export interface ProveResponse {
  errors?: (any /* api.Error */ | undefined)[];
  proof?: string;
}
/**
 * VerificationResponse model
 */
export interface VerificationResponse {
  errors?: (any /* api.Error */ | undefined)[];
  result: boolean;
}
