// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

/**
 * Application model which is initially owned by the user who created it
 */
export interface Application {
  network_id?: string /* uuid */;
  user_id?: string; // this is the user that initially created the app
  name?: string;
  description?: string;
  status?: string; // this is for enrichment purposes only
  type?: string;
  config: { [key: string]: any};
  hidden: boolean;
}
/**
 * AuthenticationResponse is returned upon successful authentication of a user (i.e., by email address)
 */
export interface AuthenticationResponse {
  user?: User;
  token?: Token;
}
/**
 * Invite model
 */
export interface Invite {
  application_id?: string /* uuid */;
  user_id?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  invitor_id?: string /* uuid */;
  invitor_name?: string;
  organization_id?: string;
  organization_name?: string;
  permissions?: number /* uint32 */;
  params?: { [key: string]: any};
}
/**
 * JSONWebKey represents the public part of a JWT
 */
export interface JSONWebKey {
  kid?: string;
  use?: string;
  n?: string;
  e?: string;
  x5c?: string[];
  fingerprint?: string;
  public_key?: string;
}
/**
 * Organization model
 */
export interface Organization {
  name?: string;
  user_id?: string;
  description?: string;
  permissions?: number /* uint32 */;
  metadata: { [key: string]: any};
  users_count?: number /* uint32 */;
}
/**
 * Token represents a bearer JWT
 */
export interface Token {
  token?: string;
  /**
   * OAuth 2 fields
   */
  access_token?: string;
  refresh_token?: string;
  scope?: string;
  /**
   * Ephemeral JWT header fields and claims; these are here for convenience and
   * are not always populated, even if they exist on the underlying token
   */
  kid?: string; // key fingerprint
  audience?: string;
  issuer?: string;
  issued_at?: string /* RFC3339 */;
  expires_at?: string /* RFC3339 */;
  expires_in?: number /* uint64 */;
  not_before_at?: string /* RFC3339 */;
  subject?: string;
  permissions?: number /* uint32 */;
  data?: { [key: string]: any};
}
/**
 * User represents a user
 */
export interface User {
  name: string;
  first_name: string;
  last_name: string;
  email: string;
  permissions?: number /* uint32 */;
  privacy_policy_agreed_at?: string /* RFC3339 */;
  terms_of_service_agreed_at?: string /* RFC3339 */;
  metadata?: { [key: string]: any};
}
