// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

/**
 * BillingAccount instances represent a virtual account with which payment methods can be
 * associated (i.e., for charging customers); currently this is a singleton-per-user
 */
export interface BillingAccount {
  application_id?: string /* uuid */;
  organization_id?: string /* uuid */;
  user_id?: string /* uuid */;
  nickname?: string;
  kyc_provider?: string;
  kyc_application_id?: string /* uuid */;
  money_service_provider?: string;
  identifier?: string;
  address?: string;
  verified?: boolean;
}
/**
 * PaymentMethod represents a tokenized or virtual means by which value can be transferred
 */
export interface PaymentMethod {
  application_id?: string /* uuid */;
  organization_id?: string /* uuid */;
  user_id?: string /* uuid */;
  nickname?: string;
  brand?: string;
  exp_month?: number /* uint8 */;
  exp_year?: number /* uint16 */;
  last4?: string;
  metadata?: any /* json.RawMessage */;
}
/**
 * Payment defines a payment request
 */
export interface Payment {
  network_id?: string /* uuid */;
  application_id?: string /* uuid */;
  organization_id?: string /* uuid */;
  user_id?: string /* uuid */;
  address?: string;
  description?: string;
  status?: string;
  type?: string;
  params: { [key: string]: any};
  provider?: string;
  value?: any /* big.Int */;
}
